[nord]
    nord0  = "#232627" 
    nord1  = "#3b4252"
    nord2  = "#434c5e"
    nord3  = "#4c566a"
    nord4  = "#d8dee9"
    nord5  = "#e5e9f0"
    nord6  = "#eceff4"
    nord7  = "#8fbcbb"
    nord8  = "#88c0d0"
    nord9  = "#81a1c1"
    nord10 = "#5e81ac"
    nord11 = "#bf616a"
    nord12 = "#d08770"
    nord13 = "#ebcb8b"
    nord14 = "#a3be8c"
    nord15 = "#b48ead"

    nord1dim  = "#373e4d"
    nord5dim  = "#aeb3bb"
    nord8dim  = "#6d96a5"
    nord9dim  = "#68809a"
    nord11dim = "#94545d"
    nord13dim = "#b29e75"
    nord14dim = "#809575"
    nord15dim = "#8c738c"


[python]
    supported = ["3.9", "3.10", "3.11", "3.12"]
    pipx = [
        "pip-run",  
        "pip-tools", 
        "poetry",  
        "shiv", 
        "pre-commit",
        "s3cmd",
        "ansible",
        "ansible-lint",
        "molecule",
        "yamllint",
        "black",
        "ruff",
    ]

[python.pyenv]
    update = "https://github.com/pyenv/pyenv-update.git"
    doctor = "https://github.com/pyenv/pyenv-doctor.git"

[rust]
    wanted = ["gign", "otadump"]

[packages.macos]
    taps = [        
        "felixkratz/formulae",
        "go-task/tap",
        "homebrew/bundle",
        "homebrew/cask",
        "homebrew/cask-fonts",
        "homebrew/command-not-found",
        "homebrew/core",
        "homebrew/services",
        "koekeishiya/formulae",
        "kreuzwerker/taps",
        "spicetify/tap",
    ]

    formulae = [
        # MacOS Window Manager
        "sketchybar",
        "skhd",
        "yabai",
        "skhd",
	    "bitwarden-cli",
	    "helm",
	    "helmfile",

        # GNU programs non-existing in macOS
        "watch",
        "wdiff",
        "wget",

        # GNU programs whose BSD counterpart is installed in macOS
        "binutils",
        "coreutils",
        "diffutils",
        "ed",
        "findutils",
        "gawk",
        "gnu-indent",
        "gnu-sed",
        "gnu-tar",
        "gnu-which",
        "grep",
        "gzip",
        "screen",

        # GNU programs existing in macOS which are outdated
        "bash",
        "gpatch",
        "less",
        "m4",
        "make",
        "nano",

        # Other common/preferred programs in GNU/Linux distributions
        "file-formula",
        "git",
        "libressl",
        "openssh",
        "rsync",
        "unzip",
        "vim",

        # General programs
        "bat",  # cat with wings
        "chezmoi",
        "cloc",
        "curl",
        "fish",
        "go-jsonnet", 
        "graphviz",
        "htop",
        "iperf3",
        "jq",
        "libpq",  # PostgreSQL
        "m1-terraform-provider-helper",  # Helper for building Terraform providers on M1
        "mas",  # Mac App Store CLI
        "neofetch",
        "nmap",
        "openapi-generator",  # Generate API clients and server stubs from OpenAPI specifications 
        "pipx",
        "privoxy",  # Web proxy with advanced filtering capabilities
        "protobuf",
        "spicetify-cli",
        "starship",
        "telnet",
        "tmux",
        "tree",
        "wireguard-tools",
        "yarn",  # JavaScript package manager
        "yq",

	"mongosh",

        # CLI programs
        "bitwarden-cli",
        "consul",
        "gh",
        "httpie",
        "teleport",
        "terraform",
        "vault",

        # Containerization
        "dive",
        "helm",
        "helmfile",
        "minikube",
        "k9s",
        "kubectx",
        "kubernetes-cli",
        "kustomize",
    ]

    casks = [
        "alt-tab",
        "android-platform-tools",
        "bitwarden",
        "db-browser-for-sqlite",
        "dbeaver-community",
        "docker",
        "flameshot",
        "font-hack-nerd-font",
        "font-jetbrains-mono-nerd-font",
        "hiddenbar",
        "kitty",
        "obsidian",
        "postman",
        "raycast",
        "spotify",
        "syncthing",
        "visual-studio-code",
        "vlc",
        "wireshark",

	    "mongodb-compass",
	    "vmware-horizon-client",
    ]

    app_store = []


[packages.arch]
    packages = [
        # Toolchain
        "base-devel",

        # User Programs
        "chezmoi",
        "fish",
        "git",
        "htop",
        "net-tools",
        "qmk",
        "starship",
        "tailscale",
        "unzip",
        "zip",
        "go-yq",
        "python-pipx",
		"android-tools",

        "kitty",
        "vlc",

        "thunar",
        "thunar-archive-plugin",
        "thunar-media-tags-plugin",
        "thunar-volman",
        "gvfs",
        "gvfs-mtp",

        "hyprland",
        "xdg-desktop-portal-hyprland",
        "polkit-kde-agent",
        "playerctl",
        "swayidle",
		"swaylock-effects",
		"sway-audio-idle-inhibit",

		"xz-static",  # otadump dep
    ]
