[nord]
    nord0  = "#232627" 
    nord1  = "#3b4252"
    nord2  = "#434c5e"
    nord3  = "#4c566a"
    nord4  = "#d8dee9"
    nord5  = "#e5e9f0"
    nord6  = "#eceff4"
    nord7  = "#8fbcbb"
    nord8  = "#88c0d0"
    nord9  = "#81a1c1"
    nord10 = "#5e81ac"
    nord11 = "#bf616a"
    nord12 = "#d08770"
    nord13 = "#ebcb8b"
    nord14 = "#a3be8c"
    nord15 = "#b48ead"

    nord1dim  = "#373e4d"
    nord5dim  = "#aeb3bb"
    nord8dim  = "#6d96a5"
    nord9dim  = "#68809a"
    nord11dim = "#94545d"
    nord13dim = "#b29e75"
    nord14dim = "#809575"
    nord15dim = "#8c738c"


[packages.macos]
    taps = [
        "homebrew/cask-fonts",
    ]

    formulae = [
        # User Programs
        "chezmoi",
        "curl",
        "fish",
        "git",
        "starship",
    ]

    casks = [
        "kitty",
        "font-jetbrains-mono-nerd-font",
    ]

    app_store = []


[packages.arch]
    packages = [
        # Toolchain
        "base-devel",

        # User Programs
        "chezmoi",
        "fish",
        "git",
        "htop",
        "net-tools",
        "qmk",
        "starship",
        "tailscale",
        "unzip",
        "zip",

        "kitty",
    ]
